server {
    listen 80;
    server_name nachodaw.com www.nachodaw.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nachodaw.com www.nachodaw.com;

    # Certificados SSL (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/nachodaw.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nachodaw.com/privkey.pem;

    # 1. Frontend y Documentación
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /documentacion {
        alias /usr/share/nginx/html/docs;
        index index.html;
    }

    # 2. Backend (PHP)
    location /api {
        root /var/www/html;
        
        rewrite ^/api/(.*)$ /$1 break;
        
        fastcgi_pass app-php:9000;
        fastcgi_index index.php;
        
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
    }
}